app/modules/movies/views.py
from flask import Blueprint, request, render_template, redirect, flash, url_for
from app.modules.movies.models import Movie, Genre, Artist
from .forms import MovieForm, ArtistForm
from flask_login import current_user
from app import db
import os
from datetime import datetime

IMAGES_UPLOADS_DIR = "/var/www/html/ITI/Python/flask/Day2/lab2/starter_project/app/static/images/avatars"


movie_blueprint = Blueprint('movies', __name__, template_folder='templates')
artist_blueprint = Blueprint('artists', __name__, template_folder='templates')

@movie_blueprint.route("/", methods=["GET"])
@movie_blueprint.route("/home", methods=["GET"])
def index():
    movies = Movie.query.order_by(Movie.id.desc()).all()
    return render_template('movies/index.html', movies=movies)


@movie_blueprint.route("/movie/<id>")
def movie(id):
    movie = Movie.query.get_or_404(id)
    return render_template('movies/movie.html', movie=movie)


@movie_blueprint.route("/movie/<id>/edit", methods=["GET", "POST"])
def movie_edit(id):
    if current_user.is_authenticated:
        movie_form = MovieForm()
        movie_form.genres.choices = [(genre.id, genre.name)
                                    for genre in Genre.query.all()]
        if request.method == "POST":
            if movie_form.validate_on_submit():
                movie = Movie.query.get(id)
                movie.title = movie_form.title.data
                movie.description = movie_form.description.data
                movie.releas_year = movie_form.year.data
                movie.genres = Genre.query.filter(
                    Genre.id.in_(movie_form.genres.data)).all()

                db.session.commit()
                flash("Movie updated successfully", "success")
                return redirect(url_for("movies.index"))

            else:
                flash("Something went wrong", "danger")
                movie = Movie.query.get(id)
                selected_genres = [genre.id for genre in movie.genres]
                return render_template("movies/movies.html",
                                    form=movie_form,
                                    movie=movie,
                                    selected_genres=selected_genres)
        else:
            movie = Movie.query.get(id)
            selected_genres = [genre.id for genre in movie.genres]
            return render_template("movies/movies.html",
                                form=movie_form,
                                movie=movie,
                                selected_genres=selected_genres)
    else:
        return render_template("auth/login.html")


@movie_blueprint.route("/movies", methods=["GET", "POST"])
def movies_form():
    if current_user.is_authenticated:
        movie_form = MovieForm()
        movie_form.genres.choices = [(genre.id, genre.name)
                                    for genre in Genre.query.all()]
        movie_form.artists.choices = [(artist.id, artist.first_name + ' ' + artist.last_name) for artist in Artist.query.all() ]
        if request.method == "POST":
            if movie_form.validate_on_submit():
                genres = Genre.query.filter(Genre.id.in_(
                    movie_form.genres.data)).all()
                movie = Movie(title=movie_form.title.data,
                            description=movie_form.description.data,
                            releas_year=movie_form.year.data,
                            genres=genres
                            )
                db.session.add(movie)
                db.session.commit()
                flash("Movie add successfully", "success")
                return redirect(url_for("movies.index"))

            else:
                return render_template("movies/movies.html", form=movie_form)
        else:
            return render_template("movies/movies.html", form=movie_form)
    else:
        # return render_template(url_for("auth.login"))
        return render_template("auth/login.html")

  
@movie_blueprint.route("/movie/<id>/delete", methods=["GET"])
def movie_delete(id):
    Movie.query.filter_by(id=id).delete()
    db.session.commit()
    return redirect(url_for("movies.index"))

# Artist routes

@artist_blueprint.route('/artists', methods=["GET"])
def artists():
    artists = Artist.query.all()
    return render_template('movies/artists.html', artists=artists)


@artist_blueprint.route("/artist/add", methods=["GET", "POST"])
def artist_form():
    artist_form = ArtistForm()
    if request.method == "POST":
        if artist_form.validate_on_submit():
            # genres = Genre.query.filter(Genre.id.in_(
            #     movie_form.genres.data)).all()
            if request.files:
                avatar = request.files['avatar']
                # print(request.files.get("avatar").content_type)
                avatar_name = ''
                if avatar:
                    avatar_name = str(datetime.now()) + avatar.filename
                    avatar.save(os.path.join(IMAGES_UPLOADS_DIR, avatar_name))   
            artist = Artist(first_name=artist_form.first_name.data,
                            last_name=artist_form.last_name.data,
                            birth_date=artist_form.birth_date.data,
                            nationality=artist_form.nationality.data,
                            avatar=avatar_name
                          )
            db.session.add(artist)
            db.session.commit()

            flash("artist added successfully", "success")
            return redirect(url_for("artists.artists"))

        else:
            return render_template("movies/add_artist.html", form=artist_form)
    else:
        return render_template("movies/add_artist.html", form=artist_form)


@artist_blueprint.route("/artist/<id>", methods=["GET", "POST"])
def artist(id):
    artist = Artist.query.get_or_404(id)
    return render_template('movies/artist.html', artist=artist)


@artist_blueprint.route("/artist/<id>/edit", methods=["GET", "POST"])
def artist_edit(id):
    artist_form = ArtistForm()
    if request.method == "POST":
        if artist_form.validate_on_submit():
            artist = Artist.query.get(id)
            artist.first_name = artist_form.first_name.data
            artist.last_name = artist_form.last_name.data
            artist.birth_date = artist_form.birth_date.data
            artist.nationality = artist_form.nationality.data
            if request.files:
                avatar = request.files['avatar']
                avatar_name = str(datetime.now()) + avatar.filename
                avatar.save(os.path.join(IMAGES_UPLOADS_DIR, avatar_name))
                artist.avatar = avatar_name
            db.session.commit()
            flash("artist updated successfully", "success")
            return redirect(url_for("artists.artists"))

        else:
            flash("Something went wrong", "danger")
            artist = Artist.query.get(id)
            return render_template("movies/add_artist.html",
                                   form=artist_form,
                                   artist=artist)
    else:
        artist = Artist.query.get(id)
        return render_template("movies/add_artist.html",
                               form=artist_form,
                               artist=artist)


@artist_blueprint.route("/artist/<id>/delete", methods=["GET"])
def artist_delete(id):
    # delete Pivot table
    Artist.query.filter_by(id=id).delete()
    db.session.commit()
    flash("artist deleted successfully", "info")
    return redirect(url_for("artists.artists"))

app/modules/movies/templates/movies/add_artist.html
{% extends "base.html" %}

{% block body %}

<div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add Artist</legend>
            <div class="form-group">
                {{ form.first_name.label(class="form-control-label") }}

                {% if form.first_name.errors %}
                    {{ form.first_name(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.first_name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {% if artist %}
                        {{ form.first_name(class="form-control form-control-lg", value=artist.first_name) }}
                    {% else %}
                        {{ form.first_name(class="form-control form-control-lg") }}
                    {% endif %}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.last_name.label(class="form-control-label") }}
                {% if form.last_name.errors %}
                    {{ form.last_name(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.last_name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {% if artist %}
                       {{ form.last_name(class="form-control form-control-lg", value=artist.last_name) }}
                    {% else %}
                        {{ form.last_name(class="form-control form-control-lg") }}
                    {% endif %}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.birth_date.label(class="form-control-label") }}
                {% if form.birth_date.errors %}
                    {{ form.birth_date(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.birth_date.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {% if artist %}
                        {{ form.birth_date(class="form-control form-control-lg", value=artist.birth_date) }}
                    {% else %}
                        {{ form.birth_date(class="form-control form-control-lg") }}
                    {% endif %}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.nationality.label(class="form-control-label") }}
                {% if form.nationality.errors %}
                    {{ form.nationality(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.nationality.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {% if artist %}
                        {{ form.nationality(class="form-control form-control-lg", value=artist.nationality) }}
                    {% else %}
                        {{ form.nationality(class="form-control form-control-lg") }}
                    {% endif %}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.avatar.label(class="form-control-label") }}
                {% if form.avatar.errors %}
                    {{ form.avatar(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.avatar.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {% if artist %}
                        {{ form.avatar(class="form-control form-control-lg", value=artist.avatar) }}
                    {% else %}
                        {{ form.avatar(class="form-control form-control-lg") }}
                    {% endif %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {% if artist %}
                {{ form.submit(class="btn btn-outline-info", value="Update") }}
            {% else %}
                {{ form.submit(class="btn btn-outline-info") }}
            {% endif %}
        </div>
    </form>
</div>

{% endblock body %}

app/modules/movies/templates/movies/artist.html
{% extends "base.html" %}
{% block body %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <small class="text-muted">{{ artist.birth_date.strftime('%Y-%m-%d') }}</small>
      </div>
      {% if artist.avatar %}
      <img height="100" width="100" class="rounded-circle" src="{{ url_for('static', filename='images/avatars/'+artist.avatar) }}" alt="">
      {% endif %}
      <h2 class="article-title">{{ artist.first_name }} {{ artist.last_name }}</h2>
      <p class="article-content">{{ artist.nationality }}</p>
      <p>Movies</p>
      {% if  artist.movies %}
        <ul>
          {% for movie in artist.movies  %}
          <li>{{movie.title}}</li>
          {% endfor %}
        </ul>
      {% else %}
        <p>No Movies</p>
      {% endif %}
      {% if current_user.is_authenticated %}
      <a href="{{ url_for('artists.artist_edit', id=artist.id) }}"><button class="btn btn-outline-primary">Edit</button></a>
      <a href="{{ url_for('artists.artist_delete', id=artist.id) }}"><button class="btn btn-danger">Delete</button></a>
      {% endif %}
    </div>
  </article>
  <!-- Modal -->

{% endblock body %}

app/modules/movies/templates/movies/artists.html
{% extends "base.html" %}
{% block body %}
{% for artist in artists %}
  <article class="media content-section">
    <div class="media-body">
      <h2 class="article-title"> <a href="{{ url_for('artists.artist', id=artist.id) }}">{{ artist.first_name }} {{ artist.last_name }}</a></h2>
      <small>{{ artist.birth_date }},  {{artist.nationality}}</small>
      {#<a href="{{ url_for('movies.movie_edit') }}"><button class="btn btn-outline-primary">Edit</button></a>
      <a href="{{ url_for('movies.movie_delete') }}"><button class="btn btn-danger">Delete</button></a>#}
    </div>
  </article>
  <!-- Modal -->
{% endfor %}
{% endblock body %}

app/modules/movies/templates/movies/index.html
{% extends "base.html" %}

{% block body %}

    {% for movie in movies %}
        <div class='movie-container'>
            <article class="media content-section">
                {#  <img class="rounded-circle movie-img" src="{{ url_for('static', filename='movie_covers/' + movie.cover) }}"> #}
                 <div class="media-body">
                   <h2><a class="movie-title" href="{{ url_for('movies.movie', id=movie.id) }}">{{ movie.title }}</a></h2>
                   <p class="movie-content">{{ movie.description }}</p>
                   <div class="movie-metadata d-flex justify-content-between">
                       <small class="text-muted">Release Year: {{ movie.releas_year.strftime('%Y-%m-%d') }}</small>
                       <span class='ml-2'>
                           {% for genre in movie.genres %}
                           <span class='badge badge-warning'>{{ genre.name }}</span>
                            {% endfor %}
                       </span>
                     </div>
                 </div>
               </article>
        </div>
    {% endfor %}

{% endblock %}

app/modules/movies/templates/movies/movie.html
{% extends "base.html" %}
{% block body %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <small class="text-muted">{{ movie.releas_year.strftime('%Y-%m-%d') }}</small>
      </div>
      <h2 class="article-title">{{ movie.title }}</h2>
      <p class="article-content">{{ movie.description }}</p>
      {% if current_user.is_authenticated %}
      <a href="{{ url_for('movies.movie_edit', id=movie.id) }}"><button class="btn btn-outline-primary">Edit</button></a>
      <a href="{{ url_for('movies.movie_delete', id=movie.id) }}"><button class="btn btn-danger">Delete</button></a>
      {% endif %}
    </div>
  </article>
  <!-- Modal -->

{% endblock body %}

app/modules/movies/templates/movies/movies.html
{% extends "base.html" %}

{% block body %}

<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add Movie</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}

                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {% if movie %}
                        {{ form.title(class="form-control form-control-lg", value=movie.title) }}
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.description.label(class="form-control-label") }}
                {% if form.description.errors %}
                    {{ form.description(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.description.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {% if movie %}
                        <textarea class="form-control form-control-lg" name="description">{{ movie.description }}</textarea>
                    {% else %}
                        {{ form.description(class="form-control form-control-lg") }}
                    {% endif %}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.year.label(class="form-control-label") }}
                {% if form.year.errors %}
                    {{ form.year(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.year.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {% if movie %}
                        {{ form.year(class="form-control form-control-lg", value=movie.releas_year.strftime('%Y-%m-%d')) }}
                    {% else %}
                        {{ form.year(class="form-control form-control-lg") }}
                    {% endif %}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.genres.label(class="form-control-label") }}
                {% if form.genres.errors %}
                    {{ form.genres(class="form-control form-control-lg is-invalid", multiple=True, size=4) }}
                    <div class="invalid-feedback">
                        {% for error in form.genres.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {% if movie %}
                        <select class="form-control form-control-lg" multiple size="4" name="genres">
                            {% for genre in form.genres.choices %}
                                {% if movie and genre[0] in selected_genres %}
                                    <option value="{{ genre[0] }}" selected>{{ genre[1] }}</option>
                                {% else %}
                                    <option value="{{ genre[0] }}">{{ genre[1] }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    {% else %}
                        {{ form.genres(class="form-control form-control-lg", size=4)}}
                    {% endif %}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.artists.label(class="form-control-label") }}
                {% if form.artists.errors %}
                    {{ form.artists(class="form-control form-control-lg is-invalid", multiple=True, size=4) }}
                    <div class="invalid-feedback">
                        {% for error in form.artists.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {% if movie %}
                        <select class="form-control form-control-lg" multiple size="4" name="artists">
                            {% for artist in form.artists.choices %}
                                {% if movie and artist[0] in selected_artists %}
                                    <option value="{{ artist[0] }}" selected>{{ artist[1] }}</option>
                                {% else %}
                                    <option value="{{ artist[0] }}">{{ artist[1] }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    {% else %}
                        {{ form.artists(class="form-control form-control-lg", size=4)}}
                    {% endif %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {% if movie %}
                {{ form.submit(class="btn btn-outline-info", value="Update") }}
            {% else %}
                {{ form.submit(class="btn btn-outline-info") }}
            {% endif %}
        </div>
    </form>
</div>

{% endblock body %}