app/modules/movies/views.py
from flask import Blueprint, request, render_template, redirect, flash, url_for
from app.modules.movies.models import Movie, Genre, Artist
from .forms import MovieForm, ArtistForm
from flask_login import current_user
from app import db
import os
from datetime import datetime

IMAGES_UPLOADS_DIR = "/var/www/html/ITI/Python/flask/Day2/lab2/starter_project/app/static/images/avatars"


movie_blueprint = Blueprint('movies', __name__, template_folder='templates')
artist_blueprint = Blueprint('artists', __name__, template_folder='templates')

@movie_blueprint.route("/", methods=["GET"])
@movie_blueprint.route("/home", methods=["GET"])
def index():
    movies = Movie.query.order_by(Movie.id.desc()).all()
    return render_template('movies/index.html', movies=movies)


@movie_blueprint.route("/movie/<id>")
def movie(id):
    movie = Movie.query.get_or_404(id)
    return render_template('movies/movie.html', movie=movie)


@movie_blueprint.route("/movie/<id>/edit", methods=["GET", "POST"])
def movie_edit(id):
    if current_user.is_authenticated:
        movie_form = MovieForm()
        movie_form.genres.choices = [(genre.id, genre.name)
                                    for genre in Genre.query.all()]
        if request.method == "POST":
            if movie_form.validate_on_submit():
                movie = Movie.query.get(id)
                movie.title = movie_form.title.data
                movie.description = movie_form.description.data
                movie.releas_year = movie_form.year.data
                movie.genres = Genre.query.filter(
                    Genre.id.in_(movie_form.genres.data)).all()

                db.session.commit()
                flash("Movie updated successfully", "success")
                return redirect(url_for("movies.index"))

            else:
                flash("Something went wrong", "danger")
                movie = Movie.query.get(id)
                selected_genres = [genre.id for genre in movie.genres]
                return render_template("movies/movies.html",
                                    form=movie_form,
                                    movie=movie,
                                    selected_genres=selected_genres)
        else:
            movie = Movie.query.get(id)
            selected_genres = [genre.id for genre in movie.genres]
            return render_template("movies/movies.html",
                                form=movie_form,
                                movie=movie,
                                selected_genres=selected_genres)
    else:
        return render_template("auth/login.html")


@movie_blueprint.route("/movies", methods=["GET", "POST"])
def movies_form():
    if current_user.is_authenticated:
        movie_form = MovieForm()
        movie_form.genres.choices = [(genre.id, genre.name)
                                    for genre in Genre.query.all()]
        movie_form.artists.choices = [(artist.id, artist.first_name + ' ' + artist.last_name) for artist in Artist.query.all() ]
        if request.method == "POST":
            if movie_form.validate_on_submit():
                genres = Genre.query.filter(Genre.id.in_(
                    movie_form.genres.data)).all()
                movie = Movie(title=movie_form.title.data,
                            description=movie_form.description.data,
                            releas_year=movie_form.year.data,
                            genres=genres
                            )
                db.session.add(movie)
                db.session.commit()
                flash("Movie add successfully", "success")
                return redirect(url_for("movies.index"))

            else:
                return render_template("movies/movies.html", form=movie_form)
        else:
            return render_template("movies/movies.html", form=movie_form)
    else:
        # return render_template(url_for("auth.login"))
        return render_template("auth/login.html")

  
@movie_blueprint.route("/movie/<id>/delete", methods=["GET"])
def movie_delete(id):
    Movie.query.filter_by(id=id).delete()
    db.session.commit()
    return redirect(url_for("movies.index"))

# Artist routes

@artist_blueprint.route('/artists', methods=["GET"])
def artists():
    artists = Artist.query.all()
    return render_template('movies/artists.html', artists=artists)


@artist_blueprint.route("/artist/add", methods=["GET", "POST"])
def artist_form():
    artist_form = ArtistForm()
    if request.method == "POST":
        if artist_form.validate_on_submit():
            # genres = Genre.query.filter(Genre.id.in_(
            #     movie_form.genres.data)).all()
            if request.files:
                avatar = request.files['avatar']
                # print(request.files.get("avatar").content_type)
                avatar_name = ''
                if avatar:
                    avatar_name = str(datetime.now()) + avatar.filename
                    avatar.save(os.path.join(IMAGES_UPLOADS_DIR, avatar_name))   
            artist = Artist(first_name=artist_form.first_name.data,
                            last_name=artist_form.last_name.data,
                            birth_date=artist_form.birth_date.data,
                            nationality=artist_form.nationality.data,
                            avatar=avatar_name
                          )
            db.session.add(artist)
            db.session.commit()

            flash("artist added successfully", "success")
            return redirect(url_for("artists.artists"))

        else:
            return render_template("movies/add_artist.html", form=artist_form)
    else:
        return render_template("movies/add_artist.html", form=artist_form)


@artist_blueprint.route("/artist/<id>", methods=["GET", "POST"])
def artist(id):
    artist = Artist.query.get_or_404(id)
    return render_template('movies/artist.html', artist=artist)


@artist_blueprint.route("/artist/<id>/edit", methods=["GET", "POST"])
def artist_edit(id):
    artist_form = ArtistForm()
    if request.method == "POST":
        if artist_form.validate_on_submit():
            artist = Artist.query.get(id)
            artist.first_name = artist_form.first_name.data
            artist.last_name = artist_form.last_name.data
            artist.birth_date = artist_form.birth_date.data
            artist.nationality = artist_form.nationality.data
            if request.files:
                avatar = request.files['avatar']
                avatar_name = str(datetime.now()) + avatar.filename
                avatar.save(os.path.join(IMAGES_UPLOADS_DIR, avatar_name))
                artist.avatar = avatar_name
            db.session.commit()
            flash("artist updated successfully", "success")
            return redirect(url_for("artists.artists"))

        else:
            flash("Something went wrong", "danger")
            artist = Artist.query.get(id)
            return render_template("movies/add_artist.html",
                                   form=artist_form,
                                   artist=artist)
    else:
        artist = Artist.query.get(id)
        return render_template("movies/add_artist.html",
                               form=artist_form,
                               artist=artist)


@artist_blueprint.route("/artist/<id>/delete", methods=["GET"])
def artist_delete(id):
    # delete Pivot table
    Artist.query.filter_by(id=id).delete()
    db.session.commit()
    flash("artist deleted successfully", "info")
    return redirect(url_for("artists.artists"))

app/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
  <!--<![endif]-->
  <head>
    {% block head %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>movies</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles.css') }}"
    />
    {% endblock %}
  </head>
  <body>
    {% include "header.html" %}
    <main class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1">
            {% with messages = get_flashed_messages(with_categories=true) %} 
                {% if messages %} 
                    {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                    {{ message }}
                    </div>
                    {% endfor %} 
                {% endif %} 
            {% endwith %} 
            
            {% block body %} {% endblock %}
        </div>
      </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  </body>
</html>

app/templates/header.html
<header class="app-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-teal fixed-top">
        <a class="navbar-brand mr-4" href="/">Movies DB</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ url_for('movies.index') }}">Home</a>
            <a class="nav-item nav-link" href="{{ url_for('artists.artists') }}">Artists</a>
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('movies.movies_form') }}">Add Movie</a>
            <a class="nav-item nav-link" href="{{ url_for('artists.artist_form') }}">Add Artist</a>
            {% endif %}
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('auth.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('auth.register') }}">Register</a>
              {% endif %} 
          </div>
        </div>
    </nav>
  </header>